
version: "3.7"
services:
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883" 
      - "9001:9001"
    volumes:
      - ./conf:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - mqtt-network

networks:
  mqtt-network:
    name: mqtt-network
